parameters:
#    sample_app.example.class: Sample\AppBundle\Example

services:
#    sample_app.example:
#        class: %sample_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
